    let progressive_ore = code.text().define([
        cmp(R5, 0x42),
        cmp(R5, 0x43).ne(),
        cmp(R5, 0x44).ne(),
        cmp(R5, 0x48).ne(),
        b(progressive_charm).ne(),
        ldr(R3, (R0, 0x4D8)),
        cmp(R3, 0),
        mov(R5, 0x42).eq(),
        b(return_label).eq(),
        ldr(R3, (R0, 0x4D4)),
        cmp(R3, 0),
        mov(R5, 0x43).eq(),
        b(return_label).eq(),
        ldr(R3, (R0, 0x4E0)),
        cmp(R3, 0),
        mov(R5, 0x44).eq(),
        mov(R5, 0x48).ne(),
        b(return_label),
    ]);